# Generated by Django 3.2.4 on 2021-07-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom_classe', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('description_classe', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('nom_departement', models.TextField(choices=[('AUCUN', 'Aucun'), ('GIT', 'Git'), ('GEM', 'Gem'), ('AERO', 'Aero'), ('GC', 'Civil')], primary_key=True, serialize=False)),
                ('mail_departement', models.EmailField(max_length=100)),
                ('numero_departement', models.TextField(max_length=100)),
                ('description_dept', models.TextField(max_length=1000)),
                ('Chef_departement_de', models.TextField(choices=[('AUCUN', 'Aucun'), ('GIT', 'Git'), ('GEM', 'Gem'), ('AERO', 'Aero'), ('GC', 'Civil')], default='AUCUN')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('prenom', models.TextField(max_length=100)),
                ('nom', models.TextField(max_length=100)),
                ('mail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UE_matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_UE', models.TextField(max_length=100)),
                ('code_UE', models.IntegerField()),
                ('concerner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departements.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='departements.utilisateur')),
                ('contact_prof', models.TextField(max_length=100)),
                ('date_d_adhesion', models.DateField()),
                ('enseigner_dans', models.ManyToManyField(to='departements.Departement')),
            ],
            bases=('departements.utilisateur',),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('nom_matiere', models.TextField(max_length=300)),
                ('code_matiere', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('coef_matiere', models.IntegerField()),
                ('credit_matiere', models.IntegerField()),
                ('quota_horaire', models.IntegerField()),
                ('description_matiere', models.TextField(max_length=1000)),
                ('appartenir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departements.ue_matiere')),
                ('enseigner_dans', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departements.departement')),
                ('enseigner_par', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departements.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='departements.utilisateur')),
                ('date_de_naissance', models.DateField()),
                ('date_dinscription', models.DateField()),
                ('lieu_de_naissance', models.TextField(max_length=100)),
                ('appartient', models.ManyToManyField(to='departements.Classe')),
            ],
            bases=('departements.utilisateur',),
        ),
    ]
