# Generated by Django 3.2.4 on 2021-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='Chef_departement_de',
        ),
        migrations.AddField(
            model_name='professeur',
            name='Chef_departement_de',
            field=models.TextField(choices=[('AUCUN', 'Aucun'), ('GIT', 'Git'), ('GEM', 'Gem'), ('AERO', 'Aero'), ('GC', 'Civil')], default='AUCUN'),
        ),
    ]
