# Generated by Django 3.2.4 on 2021-07-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0002_auto_20210715_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='enseigner_dans',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='departements.classe'),
        ),
    ]
