# Generated by Django 3.2.4 on 2021-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0003_alter_matiere_enseigner_dans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
