# Generated by Django 3.2.4 on 2021-07-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0004_alter_etudiant_date_de_naissance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ('nom',)},
        ),
    ]
