# Generated by Django 3.2.4 on 2021-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0005_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.ManyToManyField(default='GIT', to='departements.Departement'),
        ),
    ]
