# Generated by Django 3.2.4 on 2021-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0006_etudiant_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_de_naissance',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.TextField(max_length=20),
        ),
    ]
