# Generated by Django 3.2.4 on 2021-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0007_auto_20210721_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_dinscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_de_naissance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
    ]
