# Generated by Django 3.2.6 on 2021-08-14 07:36

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departements', '0009_alter_etudiant_date_dinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('date_de_naissance', models.DateField(null=True)),
                ('lieu_de_naissance', models.CharField(max_length=200)),
                ('appartient', models.ManyToManyField(to='departements.Classe')),
                ('departement', models.ManyToManyField(default='GIT', to='departements.Departement')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
